require 'rspec/core/rake_task'
RSpec::Core::RakeTask.new(:spec) do |t|
  t.pattern = Rake::FileList['spec/{aliases,classes,defines,functions,hosts,integration,plans,tasks,type_aliases,types,unit}/**/*_spec.rb']
end

require 'puppet-syntax/tasks/puppet-syntax'
PuppetSyntax.manifests_paths = ['modules/*/manifests/**/*.pp']
PuppetSyntax.templates_paths = ['modules/*/templates/**/*.{erb,epp}']
PuppetSyntax.exclude_paths = ["vendor/**/*"]

require 'puppet-lint/tasks/puppet-lint'
PuppetLint::RakeTask.new :lint do |config|
  config.pattern = PuppetSyntax.manifests_paths
  config.ignore_paths = ['modules/exim/**/*.pp']
  config.fail_on_warnings = true
end

task :test => [:syntax, :lint, :spec]

task :default => [:test]
