def git_url = 'https://github.com/Katello/hammer-cli-katello.git'
def git_ref = 'master'
def hammer_cli_git_repos = ['hammer-cli', 'hammer-cli-foreman', 'hammer-cli-foreman-tasks', 'hammer_cli_foreman_bootdisk']
def obal_package_name = 'rubygem-hammer_cli_katello'
def project_name = 'hammer-cli-katello'
def build_rpm = true
def build_deb = false
def source_type = 'gem'
def releasers = ['koji-katello']
