name    'joejulian-exim'
version '0.0.7'
source 'https://joejulian@github.com/joejulian/joejulian-exim.git'
author 'Joe Julian'
license 'GPLv3+'
summary 'Manages Exim'
description 'This puppet module manages exim'
project_page 'None'
