class jenkins_master {
  # Devel is needed for jar unpacking support
  $packages = ['java-1.8.0-openjdk-headless', 'java-1.8.0-openjdk-devel', 'fontconfig']

  # Get the list by going to /script on jenkins and running:
  # Jenkins.instance.pluginManager.plugins.toArray().sort{ plugin -> plugin.getShortName()}.each{
  #   plugin -> println ("    '${plugin.getShortName()}' => {'version' => '${plugin.getVersion()}'},")
  # }
  $plugins = {
    'Matrix-sorter-plugin'               => {'version' => '1.3'},
    'Parameterized-Remote-Trigger'       => {'version' => '3.0.7'},
    'ace-editor'                         => {'version' => '1.1'},
    'analysis-core'                      => {'version' => '1.95'},
    'analysis-model-api'                 => {'version' => '3.0.0'},
    'ansible'                            => {'version' => '1.0'},
    'ansicolor'                          => {'version' => '0.6.2'},
    'ant'                                => {'version' => '1.9'},
    'antisamy-markup-formatter'          => {'version' => '1.5'},
    'apache-httpcomponents-client-4-api' => {'version' => '4.5.5-3.0'},
    'authentication-tokens'              => {'version' => '1.3'},
    'blueocean'                          => {'version' => '1.13.2'},
    'blueocean-autofavorite'             => {'version' => '1.2.3'},
    'blueocean-bitbucket-pipeline'       => {'version' => '1.13.2'},
    'blueocean-commons'                  => {'version' => '1.13.2'},
    'blueocean-config'                   => {'version' => '1.13.2'},
    'blueocean-core-js'                  => {'version' => '1.13.2'},
    'blueocean-dashboard'                => {'version' => '1.13.2'},
    'blueocean-display-url'              => {'version' => '2.2.0'},
    'blueocean-events'                   => {'version' => '1.13.2'},
    'blueocean-git-pipeline'             => {'version' => '1.13.2'},
    'blueocean-github-pipeline'          => {'version' => '1.13.2'},
    'blueocean-i18n'                     => {'version' => '1.13.2'},
    'blueocean-jira'                     => {'version' => '1.13.2'},
    'blueocean-jwt'                      => {'version' => '1.13.2'},
    'blueocean-personalization'          => {'version' => '1.13.2'},
    'blueocean-pipeline-api-impl'        => {'version' => '1.13.2'},
    'blueocean-pipeline-editor'          => {'version' => '1.13.2'},
    'blueocean-pipeline-scm-api'         => {'version' => '1.13.2'},
    'blueocean-rest'                     => {'version' => '1.13.2'},
    'blueocean-rest-impl'                => {'version' => '1.13.2'},
    'blueocean-web'                      => {'version' => '1.13.2'},
    'bouncycastle-api'                   => {'version' => '2.17'},
    'brakeman'                           => {'version' => '0.12'},
    'branch-api'                         => {'version' => '2.1.2'},
    'build-flow-plugin'                  => {'version' => '0.20'},
    'build-keeper-plugin'                => {'version' => '1.3'},
    'build-metrics'                      => {'version' => '1.3'},
    'build-pipeline-plugin'              => {'version' => '1.5.8'},
    'build-timeout'                      => {'version' => '1.19'},
    'buildgraph-view'                    => {'version' => '1.8'},
    'bulk-builder'                       => {'version' => '1.5'},
    'checkstyle'                         => {'version' => '4.0.0'},
    'cloudbees-bitbucket-branch-source'  => {'version' => '2.4.2'},
    'cloudbees-folder'                   => {'version' => '6.7'},
    'cobertura'                          => {'version' => '1.13'},
    'code-coverage-api'                  => {'version' => '1.0.7'},
    'command-launcher'                   => {'version' => '1.3'},
    'conditional-buildstep'              => {'version' => '1.3.6'},
    'config-file-provider'               => {'version' => '3.5'},
    'configurationslicing'               => {'version' => '1.47'},
    'copy-to-slave'                      => {'version' => '1.4.4'},
    'copyartifact'                       => {'version' => '1.42'},
    'create-fingerprint'                 => {'version' => '1.2'},
    'credentials'                        => {'version' => '2.1.18'},
    'credentials-binding'                => {'version' => '1.18'},
    'custom-job-icon'                    => {'version' => '0.2'},
    'cvs'                                => {'version' => '2.14'},
    'dashboard-view'                     => {'version' => '2.10'},
    'display-url-api'                    => {'version' => '2.3.0'},
    'docker-commons'                     => {'version' => '1.13'},
    'docker-workflow'                    => {'version' => '1.17'},
    'dry'                                => {'version' => '3.0.0'},
    'durable-task'                       => {'version' => '1.29'},
    'dynamic-axis'                       => {'version' => '1.0.3'},
    'email-ext'                          => {'version' => '2.65'},
    'embeddable-build-status'            => {'version' => '2.0'},
    'external-monitor-job'               => {'version' => '1.7'},
    'favorite'                           => {'version' => '2.3.2'},
    'ghprb'                              => {'version' => '1.42.0'},
    'git'                                => {'version' => '3.9.3'},
    'git-client'                         => {'version' => '2.7.6'},
    'git-parameter'                      => {'version' => '0.9.10'},
    'git-server'                         => {'version' => '1.7'},
    'github'                             => {'version' => '1.29.4'},
    'github-api'                         => {'version' => '1.95'},
    'github-branch-source'               => {'version' => '2.4.2'},
    'github-oauth'                       => {'version' => '0.31'},
    'global-build-stats'                 => {'version' => '1.5'},
    'greenballs'                         => {'version' => '1.15'},
    'groovy'                             => {'version' => '2.2'},
    'handlebars'                         => {'version' => '1.1.1'},
    'handy-uri-templates-2-api'          => {'version' => '2.1.7-1.0'},
    'htmlpublisher'                      => {'version' => '1.18'},
    'icon-shim'                          => {'version' => '2.0.3'},
    'instant-messaging'                  => {'version' => '1.35'},
    'ircbot'                             => {'version' => '2.30'},
    'jackson2-api'                       => {'version' => '2.9.8'},
    'javadoc'                            => {'version' => '1.5'},
    'jclouds-jenkins'                    => {'version' => '2.14'},
    'jdk-tool'                           => {'version' => '1.2'},
    'jenkins-design-language'            => {'version' => '1.13.2'},
    'jira'                               => {'version' => '3.0.5'},
    'jobConfigHistory'                   => {'version' => '2.19'},
    'jquery'                             => {'version' => '1.12.4-0'},
    'jquery-detached'                    => {'version' => '1.2.1'},
    'jsch'                               => {'version' => '0.1.55'},
    'junit'                              => {'version' => '1.27'},
    'kubernetes'                         => {'version' => '1.14.9'},
    'kubernetes-credentials'             => {'version' => '0.4.0'},
    'ldap'                               => {'version' => '1.20'},
    'libvirt-slave'                      => {'version' => '1.8.5'},
    'lockable-resources'                 => {'version' => '2.4'},
    'mailer'                             => {'version' => '1.23'},
    'mapdb-api'                          => {'version' => '1.0.9.0'},
    'matrix-auth'                        => {'version' => '2.3'},
    'matrix-project'                     => {'version' => '1.14'},
    'maven-plugin'                       => {'version' => '3.2'},
    'mercurial'                          => {'version' => '2.5'},
    'metrics'                            => {'version' => '4.0.2.3'},
    'momentjs'                           => {'version' => '1.1.1'},
    'monitoring'                         => {'version' => '1.76.0'},
    'multi-slave-config-plugin'          => {'version' => '1.2.0'},
    'notification'                       => {'version' => '1.13'},
    'pam-auth'                           => {'version' => '1.4'},
    'parameterized-trigger'              => {'version' => '2.35.2'},
    'pipeline-build-step'                => {'version' => '2.8'},
    'pipeline-github-lib'                => {'version' => '1.0'},
    'pipeline-githubnotify-step'         => {'version' => '1.0.4'},
    'pipeline-graph-analysis'            => {'version' => '1.9'},
    'pipeline-input-step'                => {'version' => '2.10'},
    'pipeline-milestone-step'            => {'version' => '1.3.1'},
    'pipeline-model-api'                 => {'version' => '1.3.6'},
    'pipeline-model-declarative-agent'   => {'version' => '1.1.1'},
    'pipeline-model-definition'          => {'version' => '1.3.6'},
    'pipeline-model-extensions'          => {'version' => '1.3.6'},
    'pipeline-rest-api'                  => {'version' => '2.10'},
    'pipeline-stage-step'                => {'version' => '2.3'},
    'pipeline-stage-tags-metadata'       => {'version' => '1.3.6'},
    'pipeline-stage-view'                => {'version' => '2.10'},
    'pipeline-utility-steps'             => {'version' => '2.3.0'},
    'plain-credentials'                  => {'version' => '1.5'},
    'postbuild-task'                     => {'version' => '1.8'},
    'project-stats-plugin'               => {'version' => '0.4'},
    'promoted-builds'                    => {'version' => '3.2'},
    'pubsub-light'                       => {'version' => '1.12'},
    'pxe'                                => {'version' => '1.5'},
    'rake'                               => {'version' => '1.8.0'},
    'rebuild'                            => {'version' => '1.29'},
    'redmine'                            => {'version' => '0.21'},
    'regression-report-plugin'           => {'version' => '1.5'},
    'ruby'                               => {'version' => '1.2'},
    'ruby-runtime'                       => {'version' => '0.12'},
    'rubyMetrics'                        => {'version' => '1.6.5'},
    'run-condition'                      => {'version' => '1.2'},
    'rvm'                                => {'version' => '0.6'},
    'saferestart'                        => {'version' => '0.3'},
    'schedule-failed-builds'             => {'version' => '1.1'},
    'scm-api'                            => {'version' => '2.3.0'},
    'scm-sync-configuration'             => {'version' => '0.0.10'},
    'script-security'                    => {'version' => '1.55'},
    'slave-setup'                        => {'version' => '1.10'},
    'sse-gateway'                        => {'version' => '1.17'},
    'ssh'                                => {'version' => '2.6.1'},
    'ssh-agent'                          => {'version' => '1.17'},
    'ssh-credentials'                    => {'version' => '1.15'},
    'ssh-slaves'                         => {'version' => '1.29.4'},
    'statusmonitor'                      => {'version' => '1.3'},
    'structs'                            => {'version' => '1.17'},
    'subversion'                         => {'version' => '2.12.1'},
    'tap'                                => {'version' => '2.2.2'},
    'throttle-concurrents'               => {'version' => '2.0.1'},
    'timestamper'                        => {'version' => '1.9'},
    'token-macro'                        => {'version' => '2.7'},
    'translation'                        => {'version' => '1.16'},
    'variant'                            => {'version' => '1.2'},
    'violations'                         => {'version' => '0.7.11'},
    'warnings'                           => {'version' => '5.0.1'},
    'warnings-ng'                        => {'version' => '4.0.0'},
    'windows-slaves'                     => {'version' => '1.4'},
    'workflow-aggregator'                => {'version' => '2.6'},
    'workflow-api'                       => {'version' => '2.33'},
    'workflow-basic-steps'               => {'version' => '2.15'},
    'workflow-cps'                       => {'version' => '2.64'},
    'workflow-cps-global-lib'            => {'version' => '2.13'},
    'workflow-durable-task-step'         => {'version' => '2.29'},
    'workflow-job'                       => {'version' => '2.32'},
    'workflow-multibranch'               => {'version' => '2.21'},
    'workflow-scm-step'                  => {'version' => '2.7'},
    'workflow-step-api'                  => {'version' => '2.19'},
    'workflow-support'                   => {'version' => '3.2'},
    'xunit'                              => {'version' => '2.3.3'},
    'xvfb'                               => {'version' => '1.1.3'},
    'zentimestamp'                       => {'version' => '4.2'},
  }

  ensure_packages($packages)

  class { 'jenkins':
    install_java      => false,
    lts               => true,
    cli_remoting_free => true,
    default_plugins   => [],
    plugin_hash       => $plugins,
    config_hash       => {
      'JENKINS_JAVA_OPTIONS' => {
        'value' => '-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false -Xms2048m -Xmx2048m',
      }
    },
    require           => Package[$packages],
  }

}
