require "yaml"
require "net/smtp"

# REVIEW AND EDIT THIS SCRIPT BEFORE USE!
from = "xxx@redhat.com"

users = YAML.load_file('users.yaml')
users.each_pair do |u, d|
  puts "Spamming #{u}"
  Net::SMTP.start('smtp.corp.redhat.com', 25) do |smtp|
    smtp.open_message_stream(from, [u]) do |f|
      f.puts "From: #{from}"
      f.puts "To: #{u}"
      f.puts 'Subject: Your debugs.theforeman.org password'
      f.puts
      f.puts 'To download foreman-debug tarballs visit http://debugs.theforeman.org/'
      f.puts "as #{u} with your unique password #{d['passwd']}"
      f.puts
      f.puts '-- '
      f.puts
      f.puts "This was autogenerated e-mail, yeah..."
    end
  end
end


