#!/bin/bash

set -eu
set -o pipefail

NODE_NAME=$(hostname -f)
NODE_IDLE=$(curl --fail --silent https://ci.theforeman.org/computer/${NODE_NAME}/api/json/ | jq .idle)

if [[ $NODE_IDLE == true ]]; then
  shutdown -r 'Rebooting after applying package updates'
fi
