- job:
    name: deploy_web
    node: 'admin && sshkey'
    scm:
      - theforeman.org
    triggers:
      - github
      - pollscm: '*/5 * * * *'
    builders:
      - deploy_web
    publishers:
      - gemset_cleanup
      - ircbot_freenode
