- publisher:
    name: systest_foreman
    publishers:
    - archive:
        artifacts: 'debug/*,*.bats.out,*.tap'
        allow-empty: true
        only-successful: true
    - tap:
        results: '*.bats.out'
        fail-if-no-results: true
        failed-tests-mark-build-as-failure: true
        enable-subtests: false
        todo-is-failure: false
